# Linear Regression

### xにとってｙを一番よく説明すること変数ｗ、ｂを探す  
この場合どのくらい予測が正確なのか判断するmetric "MSE"を使います  
MSE = Mean Squared Error  

従って、
$$Loss = {(y^*-y)^2 \over n}$$

### Lossをminimizeするw、bを探したい。

Random Search (X)  
Gradient Descent (O)

$$ w_{t+1} = w_t - gradient * learning\_rate $$  
どんどんgradientが低い方向に向かって進む

SGD, Adam , Optimizer, Adagrad, SparseAdam... いろんな種類のOptimizerがある。

# Neural Network

#### Layerが1存在する場合  
$$ y = w2(act(w1 * input + b1)) + b2 $$

#### Layerが3存在する場合  
$$ y = w4(act(w3(act(w2(act(w1*input+b1))+b2))+b3))+b4 $$

Activation functionでnon-linearlityを追加する  
sigmoid, tanH, ReLU等がある

# Propagation 

## Forward & Back Prop

$$ forward = y^* = w3*act(w2*act(w1*act+b1)+b2)+b3$$
$$ loss = y^*-y = w3*act(w2*act(w1*x+b1)+b2)+b3-y$$
$$ \frac {\partial loss}{\partial w3} = act(w2*act(w1*x+b1)b2) $$
$$ \frac {\partial loss}{\partial b3} = 1 $$
$$ \frac {\partial loss}{\partial w2} = chain Rule!! $$
$$ Chain Rule = \frac {\partial z}{\partial x} = \frac {\partial z}{\partial y}\frac {\partial y}{\partial x} $$

# practice

## Workflow
### Data > Model > Ouput > Loss > Gradients > Update

### 1)Declaration

In [1]:
import torch
from torch.autograd import Variable

In [69]:
x_tensor = torch.Tensor(3,4)
x_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
x_variable = Variable(x_tensor)
x_variable

tensor([[1.3733e-14, 6.4076e+07, 2.0706e-19, 7.3909e+22],
        [2.4176e-12, 1.1625e+33, 8.9605e-01, 1.1632e+33],
        [5.6003e-02, 7.0374e+22, 5.7453e-44, 0.0000e+00]])

### 2) Variables of a Variable

In [5]:
x_variable.data

tensor([[1.3733e-14, 6.4076e+07, 2.0706e-19, 7.3909e+22],
        [2.4176e-12, 1.1625e+33, 8.9605e-01, 1.1632e+33],
        [5.6003e-02, 7.0374e+22, 5.7453e-44, 0.0000e+00]])

In [9]:
print(x_variable.grad)

None


In [10]:
print(x_variable.requires_grad)

x_variable = Variable(x_tensor, requires_grad=True)
x_variable.requires_grad

# requires_grad : この変数についてgradientの演算をするかどうかを決定する

False


True

In [17]:
x_variable = Variable(x_tensor, volatile=True)
x_variable.grad, x_variable.requires_grad, x_variable.volatile

# volatile = minimal memory usage.
# 一つのvolatileが全てのgraphのgradient必要がなくなる

D:\Users\LSH\Anaconda3\envs\cuda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  """Entry point for launching an IPython kernel.
D:\Users\LSH\Anaconda3\envs\cuda\lib\site-packages\ipykernel_launcher.py:2: UserWarning: volatile was removed (Variable.volatile is always False)
  


(None, False, False)

### 3) Graph & Variables

In [116]:
x = Variable(torch.FloatTensor(3,4), requires_grad=True)
y = x**2 + 4*x
z = 2*y+3

x.requires_grad, y.requires_grad, z.requires_grad

(True, True, True)

In [117]:
loss  = torch.FloatTensor(3,4)
z.backward(loss)

print(x.grad)
y.grad, z.grad

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


(None, None)