# Create Tensor

## Random Numbers

In [66]:
import torch

x = torch.rand(2,3)
x

tensor([[0.2164, 0.9096, 0.7329],
        [0.2473, 0.6111, 0.6874]])

In [67]:
x = torch.randperm(5)
x
# インデックスを混ぜる

tensor([3, 4, 2, 1, 0])

## Zero, Ones, Arange

In [68]:
x = torch.zeros(2,3)
x
# 0行列

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [69]:
x = torch.ones(2,3)
x
# 1行列

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [70]:
x = torch.arange(0,3,step=0.5)
x
# for文のように生成 

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

## Tensor Data Type

In [71]:
x = torch.FloatTensor(2,3)
x
# floatになっているtensorの生成

tensor([[0.0000, 0.5000, 1.0000],
        [1.5000, 2.0000, 2.5000]])

In [72]:
x = x.type_as(torch.IntTensor())
x
# Tensorのタイプ変更

tensor([[0, 0, 1],
        [1, 2, 2]], dtype=torch.int32)

In [73]:
import numpy as np

## Numpt to tensor, Tensor to Numpy

In [74]:
x1 = np.ndarray(shape=(2,3), dtype=int, buffer=np.array([1,2,3,4,5,6]))
x2 = torch.from_numpy(x1)
x2

#numpyをtensorに

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

## Tensor on CPU & GPU 

In [75]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [76]:
x_gpu = x.cuda()
x_gpu
#デプォルトは0番

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [77]:
x_cpu = x_gpu.cpu()
x_cpu

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Tensor Size

In [78]:
x = torch.FloatTensor(10,12,3,3)
x.size()
#Tensorの形を見せる

torch.Size([10, 12, 3, 3])

# Indexing, Slicing, Joining

## Indexing

In [79]:
x = torch.rand(4,3)
out = torch.index_select(x,0,torch.LongTensor([0,3]))
x,out
# 幾つのインデックスを選択

(tensor([[0.0023, 0.1984, 0.7454],
         [0.3558, 0.1317, 0.0490],
         [0.4554, 0.0479, 0.9204],
         [0.1434, 0.7964, 0.8607]]), tensor([[0.0023, 0.1984, 0.7454],
         [0.1434, 0.7964, 0.8607]]))

In [80]:
x[:,0],x[0,:],x[0:2,0:2]
#直接にインデックスを選択

(tensor([0.0023, 0.3558, 0.4554, 0.1434]),
 tensor([0.0023, 0.1984, 0.7454]),
 tensor([[0.0023, 0.1984],
         [0.3558, 0.1317]]))

In [81]:
x = torch.randn(2,3)
mask = torch.ByteTensor([[0,0,1],[0,1,0]])
out = torch.masked_select(x,mask)

x, mask, out

#maskされた項目のみ選択

(tensor([[-1.3179, -1.2377,  0.6452],
         [-1.1096, -0.4737,  0.2600]]), tensor([[0, 0, 1],
         [0, 1, 0]], dtype=torch.uint8), tensor([ 0.6452, -0.4737]))

## Joining

In [82]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
y = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])
z1 = torch.cat([x,y],dim=0)
z2 = torch.cat([x,y],dim=1)

x,y,z1,z2

#どんなdimensionに合わせるか選択してそれに応じて合わせる

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.,  2.,  3., -1., -2., -3.],
         [ 4.,  5.,  6., -4., -5., -6.]]))

## Squeezing

squeeze

## Slicing

chunk, split

# Initialization

In [83]:
import torch.nn.init as init

x1 = init.uniform(torch.FloatTensor(3,4), a=0, b=9) # ０から９まで
x2 = init.normal(torch.FloatTensor(3,4),std=0.2) # normaldistribution
x3 = init.constant(torch.FloatTensor(3,4),3.1415) # constantで

x1,x2,x3

D:\Users\LSH\Anaconda3\envs\cuda\lib\site-packages\ipykernel_launcher.py:3: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  This is separate from the ipykernel package so we can avoid doing imports until
D:\Users\LSH\Anaconda3\envs\cuda\lib\site-packages\ipykernel_launcher.py:4: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  after removing the cwd from sys.path.
D:\Users\LSH\Anaconda3\envs\cuda\lib\site-packages\ipykernel_launcher.py:5: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  """


(tensor([[6.3515, 1.3372, 7.2354, 5.4130],
         [2.9151, 0.5833, 2.4116, 2.3315],
         [3.9448, 3.8442, 5.2428, 4.6992]]),
 tensor([[ 0.2172, -0.0402,  0.0569,  0.2046],
         [-0.3027,  0.0910, -0.1359,  0.2265],
         [-0.2065,  0.0159,  0.1335,  0.3407]]),
 tensor([[3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415]]))

# Math Operations

## Arithmetic operations

In [84]:
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1,x2)

x1,x2,add,x1+x2,x1-x2

#普通の演算と同じだ。

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [85]:
x1+10, x2+10, x1*3

(tensor([[11., 12., 13.],
         [14., 15., 16.]]), tensor([[11., 12., 13.],
         [14., 15., 16.]]), tensor([[ 3.,  6.,  9.],
         [12., 15., 18.]]))

In [86]:
x1 = init.constant(torch.FloatTensor(3,4),3)
torch.pow(x1,2),x1**2

D:\Users\LSH\Anaconda3\envs\cuda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  """Entry point for launching an IPython kernel.


(tensor([[9., 9., 9., 9.],
         [9., 9., 9., 9.],
         [9., 9., 9., 9.]]), tensor([[9., 9., 9., 9.],
         [9., 9., 9., 9.],
         [9., 9., 9., 9.]]))

In [87]:
x1 = torch.FloatTensor(10,3,2)
x2 = torch.FloatTensor(10,2,5)

torch.bmm(x1,x2).size()
# batch matrix multiplication

torch.Size([10, 3, 5])